version: '3.8'

services:
  postgres:
    container_name: vacancy_management_postgres
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=vacancy_management
